# Generated by Django 3.1.1 on 2020-09-23 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.CharField(default="", max_length=250)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("prep_time", models.DurationField()),
                (
                    "food_type",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(10, "Meat"), (11, "Vegetarian"), (12, "Vegan")],
                        default=10,
                        help_text="Type of food",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimeManager",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.TimeField(auto_now=True)),
                (
                    "last_update",
                    models.TimeField(default=models.TimeField(auto_now=True)),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MenuCard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.CharField(default="", max_length=250)),
                (
                    "dish",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu_cards.dish",
                    ),
                ),
                (
                    "time_stamps",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu_cards.timemanager",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dish",
            name="time_stamps",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="menu_cards.timemanager",
            ),
        ),
    ]
