# Generated by Django 3.1.1 on 2020-09-24 07:17

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menu_cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='time_stamps',
        ),
        migrations.RemoveField(
            model_name='menucard',
            name='time_stamps',
        ),
        migrations.AddField(
            model_name='dish',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='dish',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='menucard',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='menucard',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.DeleteModel(
            name='TimeManager',
        ),
    ]
