# Generated by Django 3.1.1 on 2020-09-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_cards', '0002_auto_20200924_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='food_type',
            field=models.SmallIntegerField(blank=True, choices=[(10, 'meat'), (11, 'vegetarian'), (12, 'vegan')], default=10, help_text='Type of food'),
        ),
    ]
