# Generated by Django 3.1.1 on 2020-09-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_cards', '0002_auto_20200924_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='food_type',
            field=models.SmallIntegerField(blank=True, choices=[(10, 'Meat'), (11, 'Vegetarian'), (12, 'Vegan'), (100, 'Unknown')], default=10, help_text='Type of food'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='menucard',
            constraint=models.UniqueConstraint(fields=('dish', 'name'), name='unique_dish_name'),
        ),
    ]
