version: '3.0'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    restart: always
    build: ./src
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8070:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

volumes:
  postgres_data: