version: '3.0'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    restart: always
    build: ./src
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8070:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

  redis:
    image: redis:alpine
  celery:
    build: ./src
    command: celery -A eMenu worker -l INFO
    volumes:
      - ./src/:/usr/src/app/
    environment:
      - DEBUG=1
      - SECRET_KEY=ft!pya#zx+ayyv6(gi0+u82o(9#z41=o^t(gcgtli8=4_#*0$t
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis
  celery-beat:
    build: ./src
    command: celery -A eMenu beat -l INFO
    volumes:
      - ./src/:/usr/src/app/
    environment:
      - DEBUG=1
      - SECRET_KEY=ft!pya#zx+ayyv6(gi0+u82o(9#z41=o^t(gcgtli8=4_#*0$t
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis
volumes:
  postgres_data: