[tool.black]
line-length = 79
target-version = ['py38']
skip-string-normalization = true
exclude='''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | migrations
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''