[tool.black]
line-length = 79
target-version = ['py38']
skip-string-normalization = true
exclude='(/*migrations/)'

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
balanced_wrapping = true
line_length = 79
skip_glob = '*/migrations/[0-9]*'
lines_between_types = 1